import { useEffect, useMemo, useState } from "react";
import FAButton from "../components/floatingactionbutton";
import DashboardInterface from "../components/dashboardui";
import type { ConsoleTerminal } from "../data/consoleterminal";
import ExtraLargeModal from "../components/extralargemodal";
import { inputStyle, labelStyle } from "../utils/voltaire";
import { availableProfiles } from "../data/seeddata";
import { useNavigate } from "react-router-dom";

const DashboardUI = ({darkMode}: {darkMode: boolean}) =>{
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newConsoleTerminalData, setNewConsoleTerminalData] = useState<ConsoleTerminal>({
    sessionId: '',
    userId: '',
    title: '',
    status: 'ACTIVE', 
    contextProfileId: '',
    messages: [],
    totalTokensUsed: 0,
    createdAt: new Date().toISOString(),
  });
  const sessionNavigator = useNavigate();

  const selectedProfile = useMemo(() => {
      return availableProfiles.find(p => p.id === newConsoleTerminalData.contextProfileId);
    }, [newConsoleTerminalData.contextProfileId]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
      const { name, value } = e.target;
      setNewConsoleTerminalData(prev => ({ ...prev, [name]: value }));
  };

  const isNewConsoleTerminalValid = newConsoleTerminalData.title.trim() !== '' && newConsoleTerminalData.contextProfileId !== '';

  const handleStartSession = async () => {
    if (!selectedProfile) return;

    const newTerminalSession: Partial<ConsoleTerminal> = {
      // sessionId: UUID generated by backend
      // userId: Extracted from Cognito auth context on backend
      contextProfileId: newConsoleTerminalData.contextProfileId,
      title: newConsoleTerminalData.title,
      messages: [],
      totalTokensUsed: 0,
      status: 'ACTIVE',
    };

    console.log('Initializing Terminal Session:', newTerminalSession);
    // TODO: Send to API to create the session, then navigate to the chat interface
    sessionNavigator(`/console-terminal/session/${'mock-session-id'}`);
    
    // Reset and close
    setNewConsoleTerminalData({ 
      title: '', contextProfileId: '', sessionId: '', userId: '', 
      messages: [], totalTokensUsed: 0, status: 'ACTIVE', 
      createdAt: new Date().toISOString() });
    setIsCreateModalOpen(false);
  };


    useEffect(() => {
        document.body.style.backgroundColor = darkMode ? "#1b1c1d" : "#ffffff";
      }, 
      [darkMode]);

    return(
    <>
      <DashboardInterface darkMode={darkMode} />
      <FAButton darkMode={darkMode} onClick={() => setIsCreateModalOpen(true)} 
      icon={
      <svg  xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill={"currentColor"} viewBox={"0 0 24 24"}>
        <path d="M6 9h3v2H6zm5 0h7v2h-7zm4 4h3v2h-3zm-9 0h7v2H6z"></path>
        <path d="M12 2C6.49 2 2 6.49 2 12c0 2.12.68 4.19 1.93 5.9l-1.75 2.53c-.21.31-.24.7-.06 
        1.03.17.33.51.54.89.54h9c5.51 0 10-4.49 10-10S17.51 2 12 2m0 18H4.91L6 18.43c.26-.37.23-.88-.06-1.22A7.98 
        7.98 0 0 1 4.01 12c0-4.41 3.59-8 8-8s8 3.59 8 8-3.59 8-8 8Z"></path>
        </svg>
      } />
      <ExtraLargeModal
        isOpen={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        title="Start New RAG Session"
        icon={<i className="fa-regular fa-message"></i>}
        darkMode={darkMode}
        footer={
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem' }}>
            <button 
              onClick={() => setIsCreateModalOpen(false)}
              style={{ 
                padding: '0.75rem 1.5rem', 
                cursor: 'pointer', 
                backgroundColor: 'transparent', 
                fontFamily: 'Bodoni Moda Variable, serif',
                border: `1px solid ${darkMode ? '#4b5563' : '#d1d5db'}`, color: darkMode ? '#f9fafb' : '#111827', 
                borderRadius: '4px' }}
            >
              Cancel
            </button>
            <button 
              onClick={handleStartSession}
              disabled={!isNewConsoleTerminalValid}
              style={{ 
                padding: '0.75rem 1.5rem', 
                backgroundColor: '#0B0B45', 
                color: 'white', 
                border: 'none', 
                borderRadius: '4px',
                cursor: isNewConsoleTerminalValid ? 'pointer' : 'not-allowed',
                opacity: isNewConsoleTerminalValid ? 1 : 0.5,
                fontFamily: 'Bodoni Moda Variable, serif'
              }}
            >
              Launch Terminal
            </button>
          </div>
        }
      >
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', minHeight: '300px' }}>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            
            <div>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500, color: darkMode ? '#d1d5db' : '#374151' }}>
                Session Title <span style={{ color: '#ef4444' }}>*</span>
              </label>
              <input 
                type="text" 
                name="title"
                value={newConsoleTerminalData.title}
                onChange={handleInputChange}
                placeholder="e.g., Debugging DynamoDB Schema"
                style={inputStyle(darkMode)}
              />
              <p style={{ margin: '0.5rem 0 0', fontSize: '0.75rem', color: darkMode ? '#9ca3af' : '#6b7280' }}>
                A descriptive title to help you find this chat in your history.
              </p>
            </div>

            <div>
              <label style={labelStyle(darkMode)}>
                Select Context Profile <span style={{ color: '#ef4444' }}>*</span>
              </label>
              <select 
                name="contextProfileId"
                value={newConsoleTerminalData.contextProfileId}
                onChange={handleInputChange}
                style={inputStyle(darkMode)}
              >
                <option value="">-- Choose AI Personality --</option>
                {availableProfiles.map(profile => (
                  <option key={profile.id} value={profile.id}>
                    {profile.name}
                  </option>
                ))}
              </select>
            </div>

          </div>

          <div style={{ 
            backgroundColor: darkMode ? '#1f2937' : '#f9fafb', 
            border: `1px solid ${darkMode ? '#374151' : '#e5e7eb'}`, 
            borderRadius: '0.5rem', 
            padding: '1.5rem',
            display: 'flex',
            flexDirection: 'column'
          }}>
            
            {!selectedProfile ? (
              <div style={{ margin: 'auto', textAlign: 'center', color: darkMode ? '#6b7280' : '#9ca3af' }}>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" style={{ width: '48px', height: '48px', margin: '0 auto 1rem' }}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                </svg>
                <p>Select a Context Profile to view its configuration.</p>
              </div>
            ) : (
              <div style={{ animation: 'overlayFadeIn 0.3s ease-out' }}>
                <h3 style={{ margin: '0 0 0.5rem', color: darkMode ? '#f9fafb' : '#111827' }}>
                  {selectedProfile.name}
                </h3>
                <p style={{ margin: '0 0 1.5rem', fontSize: '0.875rem', color: darkMode ? '#9ca3af' : '#6b7280' }}>
                  {selectedProfile.description}
                </p>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                  <div>
                    <span style={{ display: 'block', fontSize: '0.75rem', color: darkMode ? '#9ca3af' : '#6b7280', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Model</span>
                    <span style={{ display: 'inline-block', marginTop: '0.25rem', padding: '0.25rem 0.5rem', backgroundColor: darkMode ? '#374151' : '#e5e7eb', borderRadius: '0.25rem', fontSize: '0.875rem', color: darkMode ? '#d1d5db' : '#374151' }}>
                      {selectedProfile.llmModelId}
                    </span>
                  </div>
                  <div>
                    <span style={{ display: 'block', fontSize: '0.75rem', color: darkMode ? '#9ca3af' : '#6b7280', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Temperature</span>
                    <span style={{ display: 'block', marginTop: '0.25rem', fontSize: '0.875rem', color: darkMode ? '#d1d5db' : '#374151' }}>
                      {selectedProfile.temperature?.toFixed(2)}
                    </span>
                  </div>
                  {selectedProfile.vectorCollectionId && (
                    <div style={{ gridColumn: 'span 2' }}>
                      <span style={{ display: 'block', fontSize: '0.75rem', color: '#10b981', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 700 }}>RAG Enabled</span>
                      <span style={{ display: 'block', marginTop: '0.25rem', fontSize: '0.875rem', color: darkMode ? '#d1d5db' : '#374151' }}>
                        Linked to: {selectedProfile.vectorCollection?.name || 'Unknown Collection'}
                      </span>
                    </div>
                  )}
                </div>

                <div>
                  <span style={{ display: 'block', fontSize: '0.75rem', color: darkMode ? '#9ca3af' : '#6b7280', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>
                    System Prompt Target
                  </span>
                  <div style={{ 
                    backgroundColor: darkMode ? '#111827' : '#ffffff', 
                    padding: '1rem', 
                    borderRadius: '0.375rem',
                    border: `1px solid ${darkMode ? '#374151' : '#e5e7eb'}`,
                    fontSize: '0.875rem',
                    color: darkMode ? '#d1d5db' : '#4b5563',
                    lineHeight: '1.5',
                    maxHeight: '150px',
                    overflowY: 'auto'
                  }}>
                    {selectedProfile.systemPrompt}
                  </div>
                </div>

              </div>
            )}
          </div>

        </div>
      </ExtraLargeModal>
    </>
    )
}

export default DashboardUI;