import { GetObjectCommand } from "@aws-sdk/client-s3";
import { ConverseCommand } from "@aws-sdk/client-bedrock-runtime";
import * as mammoth from 'mammoth';
import * as xlsx from 'xlsx';
import * as mime from 'mime-types';
import * as pdfParseNamespace from 'pdf-parse';
import { ToolExecutionContext } from './types';
import { MODEL_CREDIT_MULTIPLIERS } from '../model-credit-multipliers';
const pdf = (pdfParseNamespace as any).default || pdfParseNamespace;

export const executeAttachmentReader = async ({ toolInput, clients }: ToolExecutionContext) => {
    const { s3Uri } = toolInput;

    if (!s3Uri || !s3Uri.startsWith('s3://')) {
        return { error: "Invalid file location. You must provide a valid s3:// URI." };
    }

    try {
        // Parse S3 URI (e.g., s3://vanguard-uploads/attachments/user123/report.pdf)
        const uriParts = s3Uri.replace('s3://', '').split('/');
        const bucket = uriParts.shift()!;
        const key = uriParts.join('/');
        
        // Fetch File from S3
        const s3Response = await clients.s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
        const byteArray = await s3Response.Body?.transformToByteArray();
        if (!byteArray) throw new Error("Failed to read file bytes from S3.");

        const buffer = Buffer.from(byteArray);
        const mimeType = mime.lookup(key) || 'application/octet-stream';
        const extension = key.split('.').pop()?.toLowerCase();

        
        if (extension === 'pdf') {
            const pdfData = await pdf(buffer);
            return { type: "document", format: "pdf", content: pdfData.text, additionalCreditsUsed: 0 };
        } 
        
        if (extension === 'docx') {
            const docxData = await mammoth.extractRawText({ buffer });
            return { type: "document", format: "docx", content: docxData.value, additionalCreditsUsed: 0 };
        } 
        
        if (extension === 'xlsx' || extension === 'xls' || extension === 'csv') {
            const workbook = xlsx.read(buffer, { type: 'buffer' });
            let csvOutput = "";
            workbook.SheetNames.forEach(sheetName => {
                csvOutput += `\n--- SHEET: ${sheetName} ---\n`;
                csvOutput += xlsx.utils.sheet_to_csv(workbook.Sheets[sheetName]);
            });
            return { type: "spreadsheet", format: extension, content: csvOutput, additionalCreditsUsed: 0 };
        } 
        
        if (mimeType.startsWith('text/')) {
            return { type: "text", format: extension, content: buffer.toString('utf-8'), additionalCreditsUsed: 0 };
        }

        
        if (mimeType.startsWith('image/') || mimeType.startsWith('video/')) {
            
            const mediaBlock = mimeType.startsWith('video/') 
                ? { video: { source: { s3Location: { uri: s3Uri } } } }
                : { image: { format: extension, source: { bytes: buffer } } };

            const visionCommand = new ConverseCommand({
                modelId: "amazon.nova-lite-v1:0",
                messages: [{
                    role: "user",
                    content: [
                        mediaBlock as any,
                        { text: "Analyze this media file. Transcribe any readable text, describe the visual scene in high detail, and note any audio or speech present." }
                    ]
                }]
            });

            const visionRes = await clients.bedrockRuntime.send(visionCommand);
            const mediaDescription = visionRes.output?.message?.content?.[0]?.text;
            const subInputTokens = visionRes.usage?.inputTokens || 0;
            const subOutputTokens = visionRes.usage?.outputTokens || 0;
            const novaLiteMultiplier = MODEL_CREDIT_MULTIPLIERS["amazon.nova-lite-v1:0"] || 1;
            const subAgentCredits = Math.ceil((subInputTokens + subOutputTokens) * novaLiteMultiplier);

            return { 
                type: "media_transcription", 
                format: mimeType, 
                content: mediaDescription,
                additionalCreditsUsed: subAgentCredits,
                note: "This is a textual transcription generated by a vision sub-agent. Treat this description as the visual contents of the file."
            };
        }

        return { error: `Unsupported file format: ${extension} / ${mimeType}` };

    } catch (error: any) {
        return { error: `Attachment Parsing Error: ${error.message}` };
    }
};