import PptxGenJS from "@bapunhansdah/pptxgenjs";
import { PutObjectCommand } from "@aws-sdk/client-s3";
import { PutCommand } from "@aws-sdk/lib-dynamodb";
import { ToolExecutionContext } from "./types";

function getMediaBucketName(env: Record<string, string>): string {
    return env.MEDIA_OUTPUT_BUCKET_NAME || env.MEDIA_OUTPUT_BUCKET || "praimfaya-media-outputs";
}

async function recordRAGArtifact(
    profile: any,
    session: { userId: string; id: string; title?: string },
    fileUrl: string,
    fileType: 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT',
    dynamodb: any,
    ragArtifactsTable?: string
) {
    if (!ragArtifactsTable || !dynamodb) return;
    const fileName = fileUrl.split('/').pop() || 'presentation.pptx';
    
    try {
        await dynamodb.send(new PutCommand({
            TableName: ragArtifactsTable,
            Item: {
                id: `art_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
                userId: session.userId,
                terminalId: session.id,
                terminalTitle: session.title || profile?.name || 'Terminal Session',
                modelName: profile?.llmModelId || 'amazon.nova-pro-v1:0',
                contextProfileName: profile?.name || 'Vanguard AI',
                fileUrl: fileUrl,
                fileName: fileName,
                fileType: fileType,
                createdAt: new Date().toISOString()
            }
        }));
    } catch (err) {
        console.error("Failed to record RAG artifact telemetry:", err);
    }
}

export const executePowerPointGenerator = async ({
    toolInput,
    citations,
    clients,
    profile,
    cognitoUserId,
    sessionId,
    env
}: ToolExecutionContext) => {
    try {
        let { 
            title = "Vanguard Presentation", 
            theme = "CORPORATE", 
            layout = "LAYOUT_16x9",
            author = "Vanguard AI Agent",
            slides = [] 
        } = toolInput;

        if (!Array.isArray(slides) || slides.length === 0) {
            return { 
                error: "Invalid payload: 'slides' must be a non-empty array.",
                additionalCreditsUsed: -10 
            };
        }

        const MAX_SLIDES = 30;
        const MAX_ELEMENTS_PER_SLIDE = 20;
        
        if (slides.length > MAX_SLIDES) {
            console.warn(`[Vanguard Engine] Slide count exceeded limit. Truncating from ${slides.length} to ${MAX_SLIDES}.`);
            slides = slides.slice(0, MAX_SLIDES);
        }

        const computeCreditsUsed = 500 + (slides.length * 100);
        
        const pptx = new PptxGenJS();
        pptx.layout = layout;
        pptx.author = author;
        pptx.title = title;

        const themeConfig = getThemePalette(theme);
        pptx.defineSlideMaster({
            title: "MASTER_SLIDE",
            background: { color: themeConfig.bg },
            objects: [
                { rect: { x: 0, y: 0, w: "100%", h: 0.5, fill: { color: themeConfig.primary } } },
                { text: { text: title, options: { x: 0.5, y: 0.1, w: 5, h: 0.3, color: "FFFFFF", fontSize: 12, bold: true } } },
                { text: { text: "Generated by Vanguard AI", options: { x: "75%", y: "95%", w: "25%", h: 0.2, color: themeConfig.secondary, fontSize: 8, align: "right" } } }
            ],
            slideNumber: { x: 0.5, y: "95%", color: themeConfig.secondary, fontSize: 10 }
        });

        for (const slideData of slides) {
            const slide = pptx.addSlide({ masterName: "MASTER_SLIDE" });

            if (slideData.backgroundColor) {
                slide.background = { color: slideData.backgroundColor };
            } else if (slideData.backgroundImageUrl) {
                slide.background = { path: slideData.backgroundImageUrl };
            }

            if (slideData.transition) {
                (slide as any).transition = { 
                    type: slideData.transition.type || 'fade', 
                    speed: slideData.transition.speed || 'fast' 
                };
            }

            if (slideData.notes) slide.addNotes(slideData.notes);

            if (slideData.elements && Array.isArray(slideData.elements)) {
                const elementsToProcess = slideData.elements.slice(0, MAX_ELEMENTS_PER_SLIDE);

                for (const el of elementsToProcess) {
                    const { animation, ...opts } = el.options || {}; 

                    if (animation) {
                        (opts as any).anim = { 
                            type: animation.type || 'fade', 
                            direction: animation.direction 
                        };
                    }

                    switch (el.type) {
                        case 'TEXT':
                            slide.addText(el.content || "", opts);
                            break;
                        case 'IMAGE':
                            if (el.content) slide.addImage({ path: el.content, ...opts });
                            break;
                        case 'SHAPE':
                            const shapeType = pptx.ShapeType[el.shapeType as keyof typeof pptx.ShapeType] || pptx.ShapeType.rect;
                            slide.addShape(shapeType, opts);
                            break;
                    }
                }
            }
        }

        const buffer = await pptx.write({ outputType: "nodebuffer" }) as Buffer;

        const bucketName = getMediaBucketName(env);
        const fileName = `presentations/vanguard-${Date.now()}.pptx`;
        
        await clients.s3.send(new PutObjectCommand({
            Bucket: bucketName,
            Key: fileName,
            Body: buffer,
            ContentType: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        }));

        const fileUrl = `https://${bucketName}.s3.amazonaws.com/${fileName}`;

        await recordRAGArtifact(
            profile,
            { userId: cognitoUserId, id: sessionId, title: profile?.name },
            fileUrl,
            'DOCUMENT',
            clients.dynamodb,
            env.RAG_ARTIFACTS_TABLE_NAME
        );

        citations.push({ type: 'asset', uri: fileUrl });

        return { 
            status: "Success", 
            message: "Enterprise presentation successfully generated.",
            fileUrl: fileUrl,
            additionalCreditsUsed: -computeCreditsUsed
        };

    } catch (err: any) {
        console.error("Presentation Generation Error:", err);
        return { 
            error: `Failed to generate presentation: ${err.message}`, 
            additionalCreditsUsed: -100 
        };
    }
};

function getThemePalette(theme: string) {
    const palettes: Record<string, { bg: string, primary: string, secondary: string }> = {
        FINANCE: { bg: "FFFFFF", primary: "0B2545", secondary: "8DA9C4" },
        MARKETING: { bg: "FAFAFA", primary: "FF6B6B", secondary: "4ECDC4" },
        TECHNOLOGY: { bg: "0F172A", primary: "38BDF8", secondary: "94A3B8" },
        ENTERTAINMENT: { bg: "111111", primary: "E11D48", secondary: "FBBF24" },
        CORPORATE: { bg: "FFFFFF", primary: "1E3A8A", secondary: "64748B" }
    };
    return palettes[theme] || palettes["CORPORATE"];
}